package com.pantrybox.data.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.UUID

@Entity(tableName = "shopping_items")
data class ShoppingItem(
    @PrimaryKey
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val quantity: Double = 1.0,
    val unit: String = "pcs",
    val category: String = "Other",
    val isChecked: Boolean = false,
    val createdAt: Long = System.currentTimeMillis(),
    val isAutoGenerated: Boolean = false, // True if generated from missing ingredients
    val sourceRecipeId: String? = null // Which recipe generated this item
)